# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Emmanuel Kanati
description: "Hi I'm Emmanuel, and I'm a Data Scientist. I invite you to explore my Data Science portfolio, showcasing interesting projects with a profound emphasis on driving significant business impact. Please visit my Github & LinkedIn pages by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "London, UK"

avatar_image: "/img/Profilepic.jpg"

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/emmanuel-mawuli-kanati-41a59156/"
github: "https://github.com/ekanati"  

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

